### ISSUE TITLE
Minor checks in the input field.

### ISSUE THREAD

**Issue by tusharnankani** [Abhi-tech-09/QuickSortVisualizer#6]
- A minor check on the maximum size of the array can be implemented. 
  - I think after 3000 elements, the size becomes so small, that the sorting isn't visible and the white bars become black. 

Also, if an incorrect input is typed in the custom input, a notification of <kbd>Invalid Input</kbd> can be given.

**Comment by Abhi-tech-09** [comment]
Thanks for your feedback @tusharnankani .We made the necessary changes.
